/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIImageAndTextTableCell.h>

@class UIBezierPath, UIImageView, UITextLabel;

@interface UIPreferencesTableCell : UIImageAndTextTableCell
{
    int _cellOutline;
    id _value;
    SEL _action;
    id _target;
    UIImageView *_checkedImageView;
    UIBezierPath *_fillPath;
    UIBezierPath *_strokePath;
    UITextLabel *_valueTextLabel;
    unsigned int _radioGroupItem:1;
    unsigned int _ignoreRemoveFromSuperView:1;
    unsigned int _drawAsLabel:1;
    unsigned int _drawAsGroupTitle:1;
    unsigned int _drawsBackground:1;
    unsigned int _blueDisclosureCircle:1;
    unsigned int _checkStyle:4;
    unsigned int _superViewIsPrefTable:1;
    unsigned int _dontHighlightOnMouseDown:1;
    unsigned int _tracking:1;
    unsigned int _valueChanged:1;
    unsigned int _removeControlVisible:1;
    unsigned int _dontIndentForRemoveControl:1;
    unsigned int _checkPosition:1;
    unsigned int _truncatesTitleBeforeValue:1;
    unsigned int _reserved:14;
}

+ (id)defaultTitleFont;
+ (Class)valueTextLabelClass;
- (float)_cellInset;
- (struct CGRect)buttonBounds;
- (struct CGRect)contentBounds;
- (id)enclosingPreferencesTable;
- (void)_setSuperviewsIsPrefTable:(BOOL)fp8;
- (void)movedToSuperview:(id)fp8;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setHighlighted:(BOOL)fp8;
- (void)_setHighlightOnMouseDown:(BOOL)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)_unhighlight;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)_createBezierPathWithCornerRadius:(float)fp8 bottomRadius:(float)fp12 animating:(BOOL)fp16;
- (void)setNeedsDisplay;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)removeFromSuperview;
- (void)_invalidatePaths;
- (void)setDrawsBackground:(BOOL)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)drawBackgroundInRect:(struct CGRect)fp8 withFade:(float)fp24;
- (struct CGContext *)_createContextForCaching;
- (struct CGImage *)_createCachedPrefImage;
- (struct CGImage *)_cachedBackgroundImage;
- (void)_layoutSubviewsAnimated:(BOOL)fp8;
- (void)setCellOutline:(int)fp8;
- (int)cellOutline;
- (void)_removeContextFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)_removeContextFromSuperviewAndRedislaySelf:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (id)_copyBackgroundButtonViewWithFrame:(struct CGRect)fp8;
- (float)removeButtonAnimationDuration;
- (void)_animateRemoveControlVisible:(BOOL)fp8;
- (void)_updateButtonSizeForRemoveControlVisible:(BOOL)fp8 animated:(BOOL)fp12;
- (void)removeControlWillShowRemoveButton:(id)fp8 animated:(BOOL)fp12;
- (void)removeControlWillHideRemoveButton:(id)fp8 animated:(BOOL)fp12;
- (void)removeControl:(id)fp8 willRemoveTarget:(id)fp12;
- (id)valueColor;
- (id)outlineColor;
- (id)_getTitleColor;
- (id)valueTextLabel;
- (void)setValue:(id)fp8;
- (id)value;
- (void)setTruncatesTitleBeforeValue:(BOOL)fp8;
- (BOOL)truncatesTitleBeforeValue;
- (float)disclosureRightMargin;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (id)_checkMarkImage;
- (void)_setRadioGroupItem:(BOOL)fp8;
- (void)setCheckStyle:(int)fp8;
- (void)setCheckPosition:(int)fp8;
- (void)setChecked:(BOOL)fp8;
- (BOOL)isChecked;
- (void)setUsesBlueDisclosureCircle:(BOOL)fp8;
- (id)disclosureImage;
- (id)disclosurePressedImage;
- (void)_setDrawAsGroupTitle:(BOOL)fp8;
- (void)_setDrawAsLabel:(BOOL)fp8;
- (void)sizeToFit;
- (void)setIndentsBackgroundForRemoveControl:(BOOL)fp8;
- (BOOL)indentsBackgroundForRemoveControl;
- (id)createRemoveControl;
- (void)_layoutDisclosureIfNeeded;
- (struct CGPoint)iconInset;
- (struct CGPoint)textInset;
- (void)layoutSubviews;
- (void)setIcon:(id)fp8;
- (void)updateHighlightColors;
- (void)setSelected:(BOOL)fp8 withFade:(BOOL)fp12;
- (void)_setIgnoreRemoveFromSuperView:(BOOL)fp8;
- (void)setUserInteractionEnabled:(BOOL)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;

@end

