/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITableCell.h>

@class UIImageView, UITextLabel;

@interface UIImageAndTextTableCell : UITableCell
{
    UITextLabel *_titleTextLabel;
    UIImageView *_iconImageView;
}

+ (id)defaultTitleFont;
- (void)dealloc;
- (id)titleTextLabel;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setImage:(id)fp8;
- (id)image;
- (id)_getTitleColor;
- (void)updateHighlightColors;
- (void)setUserInteractionEnabled:(BOOL)fp8;
- (id)iconImageView;
- (struct CGPoint)textInset;
- (struct CGPoint)iconInset;
- (void)setAlignment:(int)fp8;
- (int)alignment;
- (void)layoutSubviews;
- (id)_scriptingInfo;

@end

