/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray, SBSleepProofTimer;

@interface AlarmController : NSObject {
	SBSleepProofTimer *_alarmTimer;
	NSMutableArray *_alarmList;
	NSMutableArray *_alarmsToFire;
	unsigned _isReadingAlarms : 1;
	SBSleepProofTimer *_countDownTimer;
	double _countDownUntilTime;
	NSString *_countDownSoundIdentifier;
}
+(id)sharedAlarmController;
-(void)_loadAlarms;
-(void)_saveAlarms;
-(void)_loadCountDownTimer;
-(void)_saveCountDownTimer;
-(void)_alarmChanged:(id)changed;
-(void)_resetCountDownTime;
-(id)init;
-(void)dealloc;
-(void)_significantTimeChanged:(id)changed;
-(unsigned)addAlarm:(id)alarm;
-(void)removeAlarmAtIndex:(unsigned)index;
-(id)alarms;
-(void)_scheduleAlarms;
-(void)_alarmTimeReached;
-(void)setCountDownTime:(double)time withSoundIdentifier:(id)soundIdentifier;
-(void)_countDownTimerFired;
-(double)countDownTime;
-(id)countDownTimerSoundIdentifier;
@end

