/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@protocol APSConnectionDelegate <NSObject>
-(void)connection:(id)connection didReceivePublicToken:(id)token;
-(void)connection:(id)connection didReceiveMessageForTopic:(id)topic userInfo:(id)info;
@end

