/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"


@protocol ISDownloadDelegate <NSObject>
-(void)download:(id)download encounteredError:(id)error;
-(void)downloadStatusChanged:(id)changed;
@optional
-(void)download:(id)download failedToLoadArtworkWithError:(id)error;
-(void)download:(id)download loadedArtworkImage:(CGImageRef)image;
@end

