/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@protocol ISDownloadQueueDelegate <NSObject>
-(void)downloadQueue:(id)queue changedWithRemovals:(id)removals disappearances:(id)disappearances;
@optional
-(void)downloadQueueError:(id)error;
-(void)downloadQueue:(id)queue downloadStatesChangedAtIndexes:(id)indexes;
-(void)downloadQueuePreOrdersChanged:(id)changed;
@end

