/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UIColor;

@interface RoundedBorderView : UIView {
	UIColor *_color;
}
-(id)initWithFrame:(CGRect)frame color:(id)color;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

