/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBDismissOnlyAlertItem.h"

@class UITextView;

@interface SBActivationInfoAlertItem : SBDismissOnlyAlertItem {
	UITextView *_textView;
}
+(id)activeItem;
-(id)init;
-(void)dealloc;
-(BOOL)willShowInAwayItems;
-(void)didPresentAlertSheet:(id)sheet;
-(void)_updateTextView;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_simStatusChanged:(id)changed;
-(void)willActivate;
-(void)didDeactivateForReason:(int)reason;
@end

