/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class SBStatusBarBatteryView;

@interface SBActivationView : UIView {
	UIView *_backgroundView;
	SBStatusBarBatteryView *_batteryView;
	int _mode;
}
@property(readonly, assign) int mode;
-(id)initWithFrame:(CGRect)frame mode:(int)mode;
-(void)dealloc;
@end

