/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class NSMutableArray, SBAlertDisplay, UIView, NSMutableDictionary;

@interface SBAlertWindow : UIWindow {
	UIView *_contentLayer;
	unsigned _isAnimating : 1;
	unsigned _isInvalid : 1;
	unsigned _handlerActive : 1;
	float _finalAlpha;
	SBAlertDisplay *_currentDisplay;
	NSMutableArray *_stackedAlertDisplays;
	NSMutableDictionary *_alertToDisplayMap;
}
@property(assign) BOOL handlerAlreadyActive;
@property(readonly, retain) SBAlertDisplay *currentDisplay;
+(CGRect)constrainFrameToScreen:(CGRect)screen;
-(id)initWithContentRect:(CGRect)contentRect;
-(void)dealloc;
-(BOOL)isOpaque;
-(id)stackedDisplayForAlert:(id)alert;
-(void)displayAlert:(id)alert;
-(BOOL)deactivateAlert:(id)alert;
-(int)displayCount;
-(void)dismissWindow:(id)window;
-(void)alertDisplayWillDismiss;
-(void)popInCurrentDisplay;
@end

