/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UILabel, UIImageView;

@interface SBAlertImageView : UIView {
	UIImageView *_imageView;
	UILabel *_labelView;
}
-(id)initWithFrame:(CGRect)frame errorString:(id)string;
-(void)layoutSubviews;
@end

