/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBDisplay.h"
#import "SpringBoard-Structs.h"

@class SBAlertWindow, SBAlertDisplay, NSMutableDictionary;

@interface SBAlert : SBDisplay {
	SBAlertDisplay *_display;
	NSMutableDictionary *_dictionary;
	SBAlertWindow *_deferredAlertWindow;
}
@property(retain) SBAlertDisplay *display;
+(void)registerForAlerts;
+(id)alertWindow;
+(void)test;
-(void)dealloc;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)setObject:(id)object forKey:(id)key;
-(id)objectForKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(BOOL)undimsDisplay;
-(float)finalAlpha;
-(CGRect)alertWindowRect;
-(Class)alertWindowClass;
-(void)_updateStatusBarLockAndTime;
-(void)activate;
-(void)tearDownAlertWindow:(id)window;
-(void)removeFromView;
-(void)deactivate;
-(BOOL)allowsDoubleHeightStatusBar:(BOOL)bar;
-(double)autoDimTime;
-(int)statusBarMode;
-(int)statusBarOrientation;
-(void)didAnimateLockKeypadIn;
-(void)didAnimateLockKeypadOut;
-(void)didFinishAnimatingIn;
-(void)didFinishAnimatingOut;
-(void)handleMenuButtonTap;
@end

