/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertDisplay.h"
#import <Foundation/Foundation.h>

@class SBAlert;

@interface SBAlertDisplay : UIView {
	SBAlert *_alert;
	unsigned _displaysAboveStatusBar : 1;
	unsigned _shouldAnimateIn : 1;
}
@property(retain) SBAlert *alert;
@property(assign) BOOL displaysAboveStatusBar;
@property(assign) BOOL shouldAnimateIn;
-(void)launchURL:(id)url;
-(void)dismiss;
-(void)setHandlerAlreadyActive:(BOOL)active;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
-(BOOL)isReadyToBeRemovedFromView;
@end

@interface SBAlertDisplay (PhoneNumberResolution)
+(id)imageForPerson:(void *)person display:(id)display isFullscreen:(BOOL *)fullscreen;
@end

@interface SBAlertDisplay (SIMToolkitExtensions)
+(id)alertBackgroundColor;
@end

