/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"
#import "UIModalViewDelegate.h"
#import <Foundation/NSObject.h>

@class UIModalView;

@interface SBAlertItem : NSObject <UIModalViewDelegate> {
	UIModalView *_alertSheet;
	BOOL _disallowUnlockAction;
	BOOL _orderOverSBAlert;
	BOOL _preventLockOver;
}
@property(assign) BOOL disallowsUnlockAction;
@property(assign) BOOL preventLockOver;
@property(readonly, retain) UIModalView *alertSheet;
-(Class)alertSheetClass;
-(void)dealloc;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)shouldShowInLockScreen;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)undimsScreen;
-(BOOL)unlocksScreen;
-(BOOL)togglesMediaControls;
-(BOOL)dismissOnLock;
-(BOOL)dimissOnAlertActivation;
-(BOOL)willShowInAwayItems;
-(void)cleanPreviousConfiguration;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(float)lockLabelFontSize;
-(double)autoDismissInterval;
-(void)performUnlockAction;
-(void)setOrderOverSBAlert:(BOOL)alert;
-(void)willActivate;
-(void)didActivate;
-(void)willRelockForButtonPress:(BOOL)buttonPress;
-(void)dismiss;
-(void)screenWillUndim;
-(void)willDeactivateForReason:(int)reason;
-(void)didDeactivateForReason:(int)reason;
-(id)awayItem;
@end

@interface SBAlertItem (CallFailurePredicate)
-(BOOL)isCallFailureAlertItem;
@end

