/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBRingingAlertItem.h"

@class Alarm;

@interface SBAlarmAlertItem : SBRingingAlertItem {
	Alarm *_alarm;
	BOOL _snoozeAlarm;
}
@property(retain) Alarm *alarm;
-(id)initWithAlarm:(id)alarm;
-(void)dealloc;
-(BOOL)allowsSnooze;
-(void)startSnoozingAndDeactivate;
-(void)autoMute;
-(void)willDeactivateForReason:(int)reason;
-(id)lockLabel;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)soundIdentifier;
-(id)avClientName;
-(id)avAudioCategory;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

