/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>

@class NSMutableArray;

@interface SBAppRatingsStarControl : UIControl {
	NSMutableArray *_stars;
	int _currentIndex;
}
@property(readonly, assign) int currentIndex;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(float)firstStarOffset;
-(void)layoutSubviews;
-(void)handleTouches:(id)touches withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

