/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"
#import "UIModalViewDelegate.h"

@class SBApplicationIcon;

@interface SBAppProfileNotTrustedAlertItem : SBAlertItem <UIModalViewDelegate> {
	SBApplicationIcon *_icon;
	BOOL _launchApp;
}
-(id)initWithIcon:(id)icon;
-(void)dealloc;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)didDeactivateForReason:(int)reason;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)shouldShowInLockScreen;
-(BOOL)dismissOnLock;
@end

