/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <AddressBook/AddressBook.h>

@class NSString;

@interface SBApplicationUninstallationOperation : NSOperation {
	NSString *_bundleIdentifier;
}
-(id)initWithBundleIdentifier:(id)bundleIdentifier;
-(void)dealloc;
-(void)main;
@end

