/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class NSMutableArray;

@interface SBAppContextHostView : UIView {
	NSMutableArray *_contexts;
	BOOL _hostingEnabled;
}
@property(assign, nonatomic, getter=isHostingEnabled) BOOL hostingEnabled;
-(id)initWithDefaultSize;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)description;
-(void)willOrderInContextWithId:(unsigned)id windowLevel:(float)level windowOutput:(int)output;
-(void)didOrderOutContextWithId:(unsigned)id;
-(void *)createIOSurfaceForFrame:(CGRect)frame;
-(void *)createIOSurfaceForFrame:(CGRect)frame includeAdditionalContext:(unsigned)context;
@end

