/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class NSArray;

@interface SBAwayItemsView : UIModalView {
	NSArray *_displayedItems;
	float _widestLabel;
}
+(GSFontRef)createItemTypeFont;
-(id)init;
-(void)dealloc;
-(BOOL)reloadData;
-(id)_labelForAwayItem:(id)awayItem count:(int)count;
-(BOOL)hasAwayItems;
-(void)drawItems;
-(void)drawRect:(CGRect)rect;
@end

