/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"

@class SBAwayInCallController, UIModalView, TPBottomLockBar, UIPushButton, SBAwayItemsView, SBAwaySwipeGestureRecognizer, SBActivationView, SBAwayChargingView, NSTimer, SBNowPlayingArtView, TPBottomButtonBar, NSDictionary, SBAwayDateView, SBAlertImageView, SBAwayViewPluginController, NSString, UIImage;

@interface SBAwayView : SBSlidingAlertDisplay {
	BOOL _isDimmed;
	BOOL _deferAwayItemFetching;
	BOOL _showingBlockedIndicator;
	BOOL _hasTelephony;
	BOOL _wasShowingAlertAtDismiss;
	SBAwayChargingView *_chargingView;
	SBAwayDateView *_dateView;
	SBNowPlayingArtView *_albumArtView;
	SBAwayItemsView *_awayItemsView;
	SBActivationView *_activationView;
	SBAlertImageView *_firewireWarningView;
	SBAwayViewPluginController *_awayPluginController;
	SBAwaySwipeGestureRecognizer *_gestureRecognizer;
	NSTimer *_mediaControlsTimer;
	UIImage *_controlsLCDBG;
	UIImage *_priorLCDBG;
	NSDictionary *_nowPlayingInfo;
	UIImage *_nowPlayingArt;
	NSString *_lastTrackArtPath;
	NSTimer *_blockedStatusUpdateTimer;
	UIModalView *_alertSheet;
	SBAwayInCallController *_inCallController;
	TPBottomLockBar *_lockBar;
	TPBottomButtonBar *_cancelSyncBar;
	UIPushButton *_infoButton;
}
@property(assign) BOOL dimmed;
@property(readonly, retain) SBAwayChargingView *chargingView;
@property(readonly, retain) SBAwayDateView *dateView;
@property(readonly, retain) SBAwayInCallController *inCallController;
+(id)createBottomBarForInstance:(id)instance;
+(id)lockLabels:(BOOL)labels fontSize:(float *)size;
-(void)_clearBlockedStatusUpdateTimer;
-(id)initWithFrame:(CGRect)frame;
-(void)postLockCompletedNotification:(BOOL)notification;
-(void)dealloc;
-(void)_postLockCompletedNotification;
-(void)finishedAnimatingIn;
-(void)dismiss;
-(void)finishedAnimatingOut;
-(float)durationForOthersActivation;
-(void)setBottomLockBar:(id)bar;
-(BOOL)shouldAnimateIn;
-(BOOL)shouldAnimateIconsOut;
-(void)startAnimations;
-(void)stopAnimations;
-(void)showInfoButton;
-(void)hideInfoButton;
-(void)setLockoutUIVisible:(BOOL)visible mode:(int)mode;
-(void)updateUIForRestorationState:(int)restorationState;
-(void)updateUIForResetState:(int)resetState;
-(void)addFirewireWarningView;
-(void)removeFirewireWarningView;
-(void)updateInterface;
-(void)setMiddleContentAlpha:(float)alpha;
-(void)setDrawsBlackBackground:(BOOL)background;
-(void)lockBarUnlocked:(id)unlocked;
-(void)lockBarStartedTracking:(id)tracking;
-(void)lockBarStoppedTracking:(id)tracking;
-(void)updateLockBarLabel;
-(id)currentAwayPluginController;
-(void)removePluginController:(BOOL)controller;
-(void)_setPluginControllerView:(id)view;
-(void)_setAwayViewGesturesEnabled:(BOOL)enabled;
-(void)windowGestureWasCompleted:(id)completed;
-(BOOL)shouldShowBlockedRedStatus;
-(void)_updateBlockedStatusLabel;
-(void)showBlockedStatus;
-(void)removeBlockedStatus;
-(void)_updateBlockedStatus;
-(void)removeDateView;
-(void)addDateView;
-(void)awayDateViewDidChangeTitle:(id)awayDateView;
-(BOOL)shouldShowInCallInfo;
-(void)updateInCallInfo;
-(void)_positionAwayItemsView;
-(void)hideAwayItems;
-(void)showAwayItems;
-(BOOL)hasAwayItems;
-(void)setShowingDeviceLock:(BOOL)lock duration:(float)duration;
-(void)showAlertSheet:(id)sheet;
-(void)removeAlertSheet;
-(void)slideAlertSheetOut:(BOOL)out direction:(BOOL)direction duration:(float)duration;
-(void)_batteryStatusChanged:(id)changed;
-(void)addChargingView;
-(void)hideChargingView;
-(void)clearMediaControlsTimer;
-(void)restartMediaControlsTimer;
-(void)hideMediaControls;
-(void)_hideMediaControls;
-(void)showMediaControls;
-(void)toggleMediaControls;
-(BOOL)isShowingMediaControls;
-(void)showSyncingBottomBar:(BOOL)bar;
-(void)hideSyncingBottomBar:(BOOL)bar;
-(void)hideNowPlaying;
-(id)nowPlayingArtView;
-(void)updateNowPlayingInfo:(id)info;
-(BOOL)updateNowPlayingArt:(BOOL)art;
-(void)handleRequestedAlbumArt:(id)art;
-(void)animateToShowingDeviceLock:(BOOL)showingDeviceLock;
-(void)_wirelessModemStateChanged:(id)changed;
@end

