/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSDate;

@interface SBAwayItem : NSObject {
	NSString *_title;
	NSString *_secondTitle;
	NSString *_singletonTitle;
	int _uid;
	int _type;
	NSDate *_date;
	int _count;
}
@property(retain) NSString *singletonTitle;
@property(retain) NSString *secondTitle;
@property(readonly, retain) NSString *title;
@property(readonly, assign) int uid;
@property(readonly, assign) int type;
@property(readonly, retain) NSDate *date;
@property(readonly, assign) int count;
-(id)initWithTitle:(id)title uid:(int)uid type:(int)type date:(id)date count:(int)count;
-(id)initWithTitle:(id)title uid:(int)uid type:(int)type date:(id)date;
-(void)dealloc;
-(id)description;
-(int)compare:(id)compare;
-(int)compareSortingMaskedSMSToBottom:(id)bottom;
@end

