/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class SBBatteryChargingView;

@interface SBAwayChargingView : UIView {
	SBBatteryChargingView *_chargingView;
	SBBatteryChargingView *_headsetChargingView;
	unsigned _animatingBatteries : 1;
	unsigned _updateAfterAnimation : 1;
	unsigned _showingDeviceBattery : 1;
	unsigned _showingHeadsetBattery : 1;
}
@property(readonly, retain) SBBatteryChargingView *chargingView;
@property(readonly, retain) SBBatteryChargingView *headsetChargingView;
+(CGSize)defaultSize;
+(BOOL)shouldShowDeviceBattery;
+(BOOL)shouldShowHeadsetBattery;
-(id)initWithFrame:(CGRect)frame awayView:(id)view;
-(void)dealloc;
-(void)updateInterface:(BOOL)interface;
-(void)addChargingView;
-(void)hideChargingView;
-(void)addHeadsetChargingView;
-(void)hideHeadsetChargingView;
-(CGPoint)_dualBatteryPositionForBattery:(id)battery;
-(CGPoint)_singleBatteryPositionForBattery:(id)battery;
-(void)_switchFromBattery:(id)battery toView:(id)view animate:(BOOL)animate;
-(void)_slideBattery:(id)battery toShowBattery:(id)showBattery animate:(BOOL)animate;
-(void)_slideBattery:(id)battery toHideBattery:(id)hideBattery animate:(BOOL)animate;
-(void)_finishedFadeForSwitch:(id)aSwitch finished:(BOOL)finished context:(id)context;
-(void)_finishedSlideForSlideToReveal:(id)reveal finished:(BOOL)finished context:(id)context;
-(void)_finishedHideForHideToSlide:(id)slide finished:(BOOL)finished context:(id)context;
-(void)_batteryAnimationFinished:(id)finished;
-(void)_test:(id)test;
@end

