/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UIImage, UIImageView;

@interface SBBatteryChargingView : UIView {
	int _type;
	UIImageView *_topBatteryView;
	UIImageView *_bottomBatteryView;
	UIImageView *_reflectionView;
	UIImage *_lastBatteryImage;
	int _lastBatteryIndex;
	unsigned _showReflection : 1;
}
+(CGSize)defaultSizeForType:(int)type;
+(float)batteryHeightForType:(int)type;
+(int)redChargeIndexForType:(int)type;
-(id)initWithFrame:(CGRect)frame type:(int)type;
-(void)dealloc;
-(void)setShowsReflection:(BOOL)reflection;
-(int)_currentBatteryIndex;
-(id)_imageFormatString;
-(void)_batteryStatusChanged:(id)changed;
@end

