/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBIcon.h"

@class UIWebClip;

@interface SBBookmarkIcon : SBIcon {
	UIWebClip *_webClip;
}
@property(readonly, retain) UIWebClip *webClip;
-(id)initWithWebClip:(id)webClip;
-(void)dealloc;
-(BOOL)allowsCloseBox;
-(id)icon;
-(id)displayName;
-(id)displayIdentifier;
-(id)modificationDate:(BOOL)date;
-(void)launch;
-(void)completeUninstall;
@end

