/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBIconList.h"


@interface SBButtonBar : SBIconList {
}
+(CGSize)defaultSize;
-(id)initWithFrame:(CGRect)frame;
-(int)maxIconRows;
-(float)topIconPadding;
-(float)verticalIconPadding;
-(float)horizontalInsetForCenteringRow:(int)centeringRow;
-(CGPoint)originForIconAtX:(int)x Y:(int)y;
-(id)iconAtPoint:(CGPoint)point X:(int *)x Y:(int *)y proposedOrder:(int *)order;
-(int)rowAtPoint:(CGPoint)point;
-(int)columnAtPoint:(CGPoint)point;
@end

