/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"


@interface SBCalendarIconContentsView : UIView {
	unsigned _highlighted : 1;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setHighlighted:(BOOL)highlighted;
-(void)drawRect:(CGRect)rect;
@end

