/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBCallAlertDisplay : SBSlidingAlertDisplay {
	BOOL _wasToldToStopRinging;
	BOOL _answered;
	BOOL _pendingRing;
}
@property(readonly, assign) BOOL wasToldToStopRinging;
+(id)createBottomLockBarForDisplay:(id)display;
+(id)createBottomBarForInstance:(id)instance;
-(void)dealloc;
-(void)ringOrVibrate;
-(void)stopRingingOrVibrating;
-(void)ringerChanged;
-(void)updateLCDWithName:(id)name label:(id)label breakPoint:(unsigned)point;
-(void)updateImageFromPerson:(void *)person;
-(void)updateCallInformationFromAlert;
-(void)setAlert:(id)alert;
-(BOOL)shouldEnableWirelessLCD;
-(void)checkForStatusChange;
-(void)_ringIfNecessary;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
-(void)finishedAnimatingIn;
-(id)additionalURLParameter;
-(void)answerCall:(CTCallRef)call;
-(void)answerAndRelease;
-(void)answer:(id)answer;
-(void)lockBarUnlocked:(id)unlocked;
-(void)dismiss;
-(void)ignoreAndRelease;
-(void)ignore;
-(void)handleVolumeEvent:(GSEventRef)event;
@end

