/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay {
}
+(id)createTopBarForInstance:(id)instance;
+(id)createBottomBarForInstance:(id)instance;
-(void)ignore:(id)ignore;
-(void)callBack:(id)back;
-(void)setAlert:(id)alert;
@end

