/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>

@class UIImage;

@interface SBClipCornerView : UIView {
	float _cornerRadius;
	int _rectCorner;
	CGPoint _pathOrigin;
	CGPathRef _clipPath;
	UIImage *_backgroundImage;
	CGRect _backgroundImageSubrect;
}
@property(assign, nonatomic) float cornerRadius;
@property(retain, nonatomic) UIImage *backgroundImage;
@property(assign, nonatomic) CGRect backgroundImageSubrect;
-(void)_updateCornerPath;
-(id)initWithCornerRadius:(float)cornerRadius forCorner:(int)corner;
-(void)drawRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
@end

