/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"

@class NSMutableArray, SBCompassRecalibrationView, UIWindow;

@interface SBCompassRecalibrationController : NSObject {
	NSMutableArray *_assertionPorts;
	UIWindow *_recalibrationWindow;
	SBCompassRecalibrationView *_recalibrationView;
}
+(id)sharedInstance;
+(BOOL)isCompassCalibrationWindowVisible;
-(id)init;
-(void)showHUD;
-(void)_createUI;
-(void)reorientRecalibrationHUDIfNeeded:(BOOL)needed;
-(void)removeHUD;
-(void)_animationDidStop:(id)_animation finished:(id)finished context:(void *)context;
-(void)_tearDown;
-(void)clientRequestedCompassHUD:(unsigned)hud;
-(void)_clientInvalidated:(CFMachPortRef)invalidated;
@end

