/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBRingingAlertItem.h"


@interface SBCountDownAlertItem : SBRingingAlertItem {
}
-(id)lockLabel;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)soundIdentifier;
-(id)avClientName;
-(id)avAudioCategory;
@end

