/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBIcon.h"


@interface SBDestinationHole : SBIcon {
}
+(id)sharedInstance;
-(id)_automationID;
-(id)displayIdentifier;
-(id)icon;
-(void)setDisplayedIcon:(id)icon;
@end

