/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay {
}
-(void)useEmergencyCallButton;
-(void)deviceUnlockSucceeded;
-(void)deviceUnlockCanceled;
-(void)alertDisplayWillBecomeVisible;
-(void)dismiss;
-(float)delayForOthersActivation;
-(float)durationForOthersActivation;
@end

