/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBDismissOnlyAlertItem : SBAlertItem {
	NSString *_title;
	NSString *_body;
	double _autoDismissInterval;
}
@property(assign) double autoDismissInterval;
@property(retain) NSString *title;
@property(retain) id bodyText;
-(id)initWithTitle:(id)title body:(id)body;
-(void)dealloc;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
@end

