/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"


@interface SBDiskSpaceAlertItem : SBAlertItem {
}
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)shouldShowInEmergencyCall;
@end

