/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "ISDownloadQueueDelegate.h"

@class ISDownloadQueue;

@interface SBDownloadController : NSObject <ISDownloadQueueDelegate> {
	ISDownloadQueue *_downloadQueue;
}
@property(readonly, retain) ISDownloadQueue *downloadQueue;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)downloadQueue:(id)queue changedWithRemovals:(id)removals disappearances:(id)disappearances;
-(void)_showDownloadQueueError;
-(void)downloadQueueError:(id)error;
-(BOOL)checkQueue;
-(id)currentDownloads;
-(void)_networkUsageChanged:(id)changed;
@end

