/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>


@interface SBDownloadingProgressBar : UIImageView {
	UIImageView *_clipView;
	UIImageView *_fillView;
	float _progress;
}
@property(assign) float progress;
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)trackImage;
-(id)fillImage;
-(void)updateFill;
@end

