/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "ISDownloadDelegate.h"
#import "SBIcon.h"

@class NSString, ISDownload, ISDownloadStatus, SBDownloadingProgressBar;

@interface SBDownloadingIcon : SBIcon <ISDownloadDelegate> {
	NSString *_displayID;
	NSString *_bundleID;
	ISDownload *_download;
	SBDownloadingProgressBar *_progressView;
	float _progress;
	BOOL _installing;
	BOOL _wasUninstalledByUser;
	ISDownloadStatus *_lastStatus;
}
@property(retain) id displayIdentifier;
@property(retain) NSString *bundleID;
@property(retain) ISDownload *download;
+(id)displayIdentifierForDownloadUniqueID:(id)downloadUniqueID;
+(id)displayIdentifierForDownload:(id)download;
-(id)initWithDisplayIdentifier:(id)displayIdentifier;
-(id)initWithDownload:(id)download;
-(void)dealloc;
-(id)description;
-(id)icon;
-(id)modificationDate:(BOOL)date;
-(void)setDisplayedIcon:(id)icon;
-(void)updateDisplayName;
-(BOOL)shouldEllipsizeLabel;
-(BOOL)shouldKernLabel;
-(id)displayName;
-(void)launch;
-(BOOL)allowsCloseBox;
-(void)closeBoxClicked:(id)clicked;
-(void)completeUninstall;
-(void)download:(id)download encounteredError:(id)error;
-(void)download:(id)download loadedArtworkImage:(CGImageRef)image;
-(void)downloadStatusChanged:(id)changed;
-(void)retry;
-(void)remove;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(void)_reloadIcon;
-(void)_showAlertForError:(id)error;
@end

