/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class UIModalView;

@interface SBFlippyAlertItem : SBAlertItem {
	UIModalView *_frontAlertSheet;
	UIModalView *_backAlertSheet;
	BOOL _showingBack;
	BOOL _isLocked;
	BOOL _requirePasscode;
}
@property(readonly, retain) UIModalView *frontAlertSheet;
@property(readonly, retain) UIModalView *backAlertSheet;
-(Class)frontAlertSheetClass;
-(Class)backAlertSheetClass;
-(Class)alertSheetClass;
-(id)createFrontAlertSheet;
-(id)createBackAlertSheet;
-(id)alertSheet;
-(void)dealloc;
-(void)cleanPreviousConfiguration;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)configureFront:(BOOL)front requirePasscodeForActions:(BOOL)actions;
-(void)configureBack:(BOOL)back requirePasscodeForActions:(BOOL)actions;
-(void)flip;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

