/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>


@interface SBIconScrollView : UIScrollView {
}
-(BOOL)cancelTouchTracking;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(void)setContentOffset:(CGPoint)offset;
@end

