/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class SBButtonBar, NSMutableArray, SBImageCache, NSDictionary, NSSet, NSMutableDictionary;

@interface SBIconModel : NSObject {
	NSDictionary *_previousIconState;
	NSMutableArray *_iconLists;
	SBButtonBar *_buttonBar;
	NSMutableDictionary *_allIcons;
	NSSet *_hiddenIconTags;
	NSSet *_visibleIconTags;
	SBImageCache *_iconImageCache;
	SBImageCache *_smallIconImageCache;
}
@property(readonly, retain) NSMutableArray *iconLists;
@property(readonly, retain) SBButtonBar *buttonBar;
@property(readonly, retain) NSMutableDictionary *allIcons;
+(id)sharedInstance;
+(int)maxIconListCount;
-(id)init;
-(void)dealloc;
-(void)localeChanged;
-(void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
-(BOOL)isIconVisible:(id)visible;
-(void)replaceDownloadingDisplayIdentifiers:(id)identifiers withDisplayIdentifiers:(id)displayIdentifiers;
-(void)_completedUninstall:(id)uninstall;
-(id)addDownloadingIconForDownload:(id)download;
-(id)addDownloadingIconForDisplayIdentifier:(id)displayIdentifier;
-(void)removeAppForDownloadingIcon:(id)downloadingIcon;
-(id)_addBookmarkIconForWebClip:(id)webClip;
-(id)addBookmarkIconForWebClip:(id)webClip;
-(void)reloadIconImage:(id)image;
-(void)reloadIconImageForDisplayIdentifier:(id)displayIdentifier;
-(void)_purgeAndSaveCachedImages;
-(void)_purgeAndSaveCachedImages:(id)images;
-(void)cacheImagesForIcon:(id)icon;
-(void)_cacheImagesForIcon:(id)icon small:(BOOL)small;
-(id)getCachedImagedForIcon:(id)icon smallIcon:(BOOL)icon2;
-(void)_addIconForApplication:(id)application;
-(void)addIconForApplication:(id)application;
-(void)loadAllIcons;
-(id)visibleIconIdentifiers;
-(id)iconForDisplayIdentifier:(id)displayIdentifier;
-(id)iconState;
-(id)_iconState;
-(void)noteIconStateChangedExternally;
-(int)indexOfIconList:(id)iconList;
-(void)createIconLists;
-(void)uninstallBookmarkIcon:(id)icon;
-(id)iconListContainingIcon:(id)icon;
-(id)iconListContainingIconWithDisplayIdentifier:(id)displayIdentifier;
-(id)addEmptyIconList;
-(void)removeEmptyIconList:(id)list;
-(void)compactIconLists;
-(id)firstAvailableIconListX:(int *)x Y:(int *)y;
-(BOOL)iconPositionInPlatformState:(id)platformState X:(int *)x Y:(int *)y inIconListNumber:(int *)iconListNumber;
-(void)clearPreviousIconState;
-(void)addNewIconToDesignatedLocation:(id)designatedLocation animate:(BOOL)animate scrollToList:(BOOL)list saveIconState:(BOOL)state;
-(void)_addNewIconToDesignatedLocation:(id)designatedLocation animate:(BOOL)animate scrollToList:(BOOL)list saveIconState:(BOOL)state;
-(BOOL)_iconListsAreDirty;
-(void)deleteIconState;
-(void)_writeIconState;
-(void)saveIconState;
-(void)_replaceAppIconsWithDownloadingIcons;
-(void)_replaceAppIconWithDownloadingIcon:(id)downloadingIcon sourceList:(id)list;
-(void)relayout;
-(void)uninstallApplicationIcon:(id)icon;
@end

