/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>

@class NSString;

@interface SBIconLabel : UIControl {
	NSString *_label;
	unsigned _drawMoreLegibly : 1;
	unsigned _inDock : 1;
	unsigned _ellipsesText : 1;
	unsigned _kerningAllowed : 1;
	unsigned _textMightOverlap : 1;
}
-(id)initWithSize:(CGSize)size label:(id)label;
-(void)dealloc;
-(void)setInDock:(BOOL)dock;
-(void)setEllipsesText:(BOOL)text;
-(void)setKerningAllowed:(BOOL)allowed;
-(void)drawRect:(CGRect)rect;
@end

