/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>
#import <UIKit/UIView.h>

@class SBIconBadge, NSTimer, UIPushButton, SBIconLabel, UIImageView, SBIconImageView;

@interface SBIcon : UIView {
	SBIconImageView *_image;
	UIImageView *_reflection;
	UIView *_grayFilterView;
	SBIconBadge *_badge;
	id _badgeNumberOrString;
	SBIconLabel *_label;
	UIPushButton *_closeBox;
	unsigned _isShowingImages : 1;
	unsigned _drawsLabel : 1;
	unsigned _isHidden : 1;
	unsigned _isRevealable : 1;
	unsigned _inDock : 1;
	unsigned _isGrabbed : 1;
	unsigned _isGrabbing : 1;
	unsigned _highlighted : 1;
	unsigned _isJittering : 1;
	unsigned _allowJitter : 1;
	unsigned _touchDownInIcon : 1;
	NSTimer *_delayedUnhighlightTimer;
	CGPoint _unjitterPoint;
	CGPoint _grabPoint;
	NSTimer *_grabTimer;
}
@property(assign) BOOL isRevealable;
@property(assign, getter=isHighlighted) BOOL highlighted;
@property(assign, getter=isInDock) BOOL inDock;
@property(assign) BOOL allowJitter;
@property(assign) BOOL isShowingCloseBox;
+(CGSize)defaultIconSize;
+(void)enqueueReusableIconImageView:(id)view;
+(id)dequeueReusableIconImageView;
+(id)_jitterPositionAnimation;
+(id)_jitterTransformAnimation;
-(id)initWithDefaultSize;
-(void)dealloc;
-(void)localeChanged;
-(void)showIconAnimationDidStop:(id)showIconAnimation didFinish:(id)finish icon:(id)icon;
-(void)setIsHidden:(BOOL)hidden animate:(BOOL)animate;
-(BOOL)isHidden;
-(id)displayName;
-(int)localizedCompareDisplayNames:(id)names;
-(id)displayIdentifier;
-(id)modificationDate:(BOOL)date;
-(id)tags;
-(BOOL)launchEnabled;
-(void)setDisplayedIcon:(id)icon;
-(id)icon;
-(id)smallIcon;
-(CGContextRef)_createIconImageBitmapContextForSmallIcon:(BOOL)smallIcon;
-(id)reflectedIcon:(BOOL)icon;
-(BOOL)isShowingImages;
-(void)setShowsImages:(BOOL)images;
-(void)updateLabelOrigin;
-(BOOL)shouldEllipsizeLabel;
-(BOOL)shouldKernLabel;
-(void)setDrawsLabel:(BOOL)label;
-(void)updateLabelKerningAndEllipsing;
-(int)badgeValue;
-(void)setBadge:(id)badge;
-(id)_automationID;
-(BOOL)pointMostlyInside:(CGPoint)inside withEvent:(id)event;
-(id)darkenedIcon:(id)icon alpha:(float)alpha;
-(void)setHighlighted:(BOOL)highlighted delayUnhighlight:(BOOL)unhighlight;
-(void)_delayedUnhighlight;
-(void)setOrigin:(CGPoint)origin;
-(void)setIsJittering:(BOOL)jittering;
-(void)removeAllIconAnimations;
-(void)setIconPosition:(CGPoint)position;
-(double)grabDurationForEvent:(id)event;
-(void)setIsGrabbed:(BOOL)grabbed;
-(BOOL)_shouldLockItemsInStoreDemoMode;
-(void)grabTimerFired;
-(void)cancelGrabTimer;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id)dictionaryRepresentation;
-(void)launch;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(BOOL)allowsCloseBox;
-(void)hideCloseBoxAnimationDidStop:(id)hideCloseBoxAnimation didFinish:(id)finish closeBox:(id)box;
-(void)closeBoxClicked:(id)clicked;
-(void)completeUninstall;
-(id)description;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
@end

