/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */



@protocol SBIconListPageControlDelegate
-(void)pageControl:(id)control didRecieveTouchInDirection:(int)direction;
@end

