/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray, NSMutableDictionary;

@interface SBImageCache : NSObject {
	NSString *_path;
	unsigned _width;
	unsigned _height;
	unsigned _imageSize;
	int _fd;
	NSMutableDictionary *_keysToIndexes;
	NSMutableDictionary *_keysToModDates;
	NSMutableArray *_freeList;
	BOOL _dirty;
}
-(id)initWithName:(id)name imageWidth:(unsigned)width imageHeight:(unsigned)height;
-(void)dealloc;
-(long long)_offsetForIndex:(unsigned)index;
-(id)_metadataPath;
-(id)imageForKey:(id)key;
-(id)modificationDateForKey:(id)key;
-(void)_markDirty;
-(void)setBitmapImageData:(void *)data forKey:(id)key modificationDate:(id)date;
-(void)removeImageForKey:(id)key;
-(id)allKeys;
-(void)save;
@end

