/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBAlertItem.h"

@class NSString;

@interface SBInvitationAlertItem : SBAlertItem {
	NSString *_title;
	NSString *_organizer;
	double _startDate;
	double _endDate;
	int _eventId;
	BOOL _allDay;
	BOOL _floats;
	int _count;
	int _status;
}
@property(readonly, assign) int eventId;
@property(readonly, assign) int count;
@property(readonly, assign) int status;
+(id)activeInvitationAlertItems;
+(void)_addActiveItem:(id)item;
+(void)_removeActiveItem:(id)item;
+(void)registerForAlerts;
+(void)_significantTimeChange;
+(CFDateFormatterRef)_customFormatter;
-(id)init;
-(id)initWithCount:(int)count;
-(id)initWithTitle:(id)title organizerName:(id)name startDate:(double)date endDate:(double)date4 floats:(BOOL)floats allDay:(BOOL)day eventId:(int)id status:(int)status;
-(void)dealloc;
-(void)didDeactivateForReason:(int)reason;
-(id)_stringForTime:(XXStruct_fhKmAA)time;
-(id)_stringForDateTime:(XXStruct_fhKmAA)dateTime timeZone:(CFTimeZoneRef)zone;
-(id)_dateString;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(void)didPresentAlertSheet:(id)sheet;
-(void)revealEvent;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)performUnlockAction;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)willShowInAwayItems;
@end

