/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBApplicationIcon.h"


@interface SBInstalledApplicationIcon : SBApplicationIcon {
}
-(BOOL)allowsCloseBox;
-(void)completeUninstall;
-(BOOL)hasBeenSyncedBackToITunes;
-(id)ratingsAlertTitle;
-(id)ratingsAlertBody;
-(id)ratingsAlertSkipTitle;
-(id)ratingsAlertRateButtonTitle;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
@end

