/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSString, SBDisplay;

@interface SBLaunchAlertItem : SBAlertItem {
	SBDisplay *_associatedDisplay;
	int _type;
	NSString *_bundleID;
	BOOL _isDataAlert;
	BOOL _usesCellNetwork;
}
-(id)initWithLaunchAlertType:(int)launchAlertType dataAlert:(BOOL)alert usesCellNetwork:(BOOL)network bundleID:(id)id;
-(void)dealloc;
-(void)setAssociatedWithDisplay:(id)display;
-(void)_displayDeactivated:(id)deactivated;
-(BOOL)dismissOnLock;
-(id)_customAirplaneModeAlertPrompt;
-(id)alertSheet;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

