/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>

@class NSTimer, NSDictionary;

@interface SBMediaController : NSObject {
	int _manualVolumeChangeCount;
	NSDictionary *_nowPlayingInfo;
	float _pendingVolumeChange;
	NSTimer *_volumeCommitTimer;
	BOOL _debounceVolumeRepeat;
}
@property(assign) float volume;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)setNowPlayingInfo:(id)info;
-(BOOL)hasTrack;
-(BOOL)isFirstTrack;
-(BOOL)isLastTrack;
-(BOOL)isPlaying;
-(BOOL)isMovie;
-(BOOL)isTVOut;
-(id)nowPlayingArtist;
-(id)nowPlayingTitle;
-(id)nowPlayingAlbum;
-(BOOL)changeTrack:(int)track;
-(BOOL)beginSeek:(int)seek;
-(BOOL)endSeek:(int)seek;
-(BOOL)togglePlayPause;
-(void)_changeVolumeBy:(float)by;
-(float)_calcButtonRepeatDelay;
-(void)increaseVolume;
-(void)decreaseVolume;
-(void)cancelVolumeEvent;
-(void)handleVolumeEvent:(GSEventRef)event;
-(void)_registerForAVSystemControllerNotifications;
-(void)_unregisterForAVSystemControllerNotifications;
-(void)_serverConnectionDied:(id)died;
-(void)_systemVolumeChanged:(id)changed;
-(void)_cancelPendingVolumeChange;
-(void)_commitVolumeChange:(id)change;
-(void)_delayedExtendSleepTimer;
@end

