/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"


@interface SBMMSInformationMissingAlertItem : SBAlertItem {
	int _alertType;
}
@property(assign, nonatomic) int alertType;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_showNetworkPrefs;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

