/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class SBIconList, SBIcon;

@interface SBMovePlan : NSObject {
	SBIcon *_icon;
	SBIconList *_source;
	SBIconList *_destination;
	int _x;
	int _y;
}
@property(readonly, retain) SBIcon *icon;
@property(readonly, retain) SBIconList *source;
@property(readonly, retain) SBIconList *destination;
@property(readonly, assign) int x;
@property(readonly, assign) int y;
-(id)initWithIcon:(id)icon x:(int)x y:(int)y source:(id)source destination:(id)destination;
-(void)dealloc;
@end

