/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"


@interface SBNetworkReselectionAlert : SBAlert {
}
+(void)registerForAlerts;
+(void)test;
@end

