/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBPhoneAlertItem.h"


@interface SBNetworkReselectionAlertItem : SBPhoneAlertItem {
}
-(id)init;
-(void)_showPrefs;
-(id)lockLabel;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

