/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UIButton, UILabel, UISlider;

@interface SBNowPlayingAlertSheet : UIModalView {
	CGRect normalSliderFrame;
	CGRect narrowSliderFrame;
	UIButton *routeButton;
	UISlider *volumeSlider;
	UILabel *routeLabel;
}
@property(assign, nonatomic) CGRect normalSliderFrame;
@property(assign, nonatomic) CGRect narrowSliderFrame;
@property(retain, nonatomic) UISlider *volumeSlider;
@property(retain, nonatomic) UIButton *routeButton;
@property(retain, nonatomic) UILabel *routeLabel;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_positionControlButton:(int)button withFloor:(float)floor;
-(void)showRouteButtonAnimated:(BOOL)animated;
-(void)hideRouteButtonAnimated:(BOOL)animated;
-(void)showVolumeSlider;
-(void)hideVolumeSlider;
-(void)layout;
@end

