/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"


@interface SBNowPlayingAlertItemPushButton : UIPushButton {
	float _yOffset;
	float _xOffset;
}
-(id)initWithImage:(id)image;
-(void)setYOffset:(float)offset;
-(void)setXOffset:(float)offset;
-(CGRect)hitRect;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

