/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>

@class UIImageView;

@interface SBNowPlayingArtView : UIView {
	UIImageView *_imageView;
	UIView *_reflection;
}
-(void)dealloc;
-(void)setAlbumArtImage:(id)image maxSize:(float)size;
-(id)albumArtImage;
-(void)setReflectionVisible:(BOOL)visible withDuration:(float)duration;
@end

