/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"
#import "UITextFieldDelegate.h"
#import "SpringBoard-Structs.h"


@interface SBPasscodeAlertItem : SBAlertItem <UITextFieldDelegate> {
	int _mode;
	int _unlockScreenType;
}
-(id)initWithPasscodeMode:(int)passcodeMode unlockScreenType:(int)type;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)returnKeyPressed:(id)pressed;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)shouldShowInLockScreen;
-(void)dismiss;
-(void)_setErrorString:(id)string;
@end

