/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"


@interface SBPartialDownloadRemovedAlertItem : SBAlertItem {
	BOOL _allRemoved;
}
-(id)initWithAllDownloadsRemoved:(BOOL)allDownloadsRemoved;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)shouldShowInLockScreen;
@end

