/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, SBPasscodeAlertItem;

@interface SBPasscodeController : NSObject {
	SBPasscodeAlertItem *_alertItem;
	int _mode;
	NSString *_password;
	NSString *_originalPassword;
	int _unlockScreenType;
}
+(id)sharedInstance;
-(void)dealloc;
-(void)forceUserToChangePasscode;
-(void)_passwordEntered:(id)entered;
@end

