/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>


@interface SBPasscodeField : UIPasscodeField {
	float _width;
	BOOL _isAlphanumericField;
}
-(id)okButton;
-(void)setIsAlphanumericField:(BOOL)field;
-(void)_updateFields;
-(void)textFieldDidResignFirstResponder:(id)textField;
-(void)_textDidChange;
-(id)entryField;
-(void)setButtonWidth:(float)width;
-(void)adjustOKButtonFrame;
@end

