/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBPhoneAlertItem : SBAlertItem {
	NSString *_bodyText;
	NSString *_title;
}
-(id)initWithTitle:(id)title bodyText:(id)text;
-(void)dealloc;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
@end

