/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert {
	int _count;
	id _delegate;
	SBPowerDownView *_powerDownView;
	BOOL _isFront;
}
@property(readonly, retain) SBPowerDownView *powerDownView;
+(id)sharedInstance;
-(void)dealloc;
-(double)autoLockTime;
-(BOOL)isOrderedFront;
-(void)orderFront;
-(void)orderOut;
-(void)activate;
-(void)_restoreIconListIfNecessary;
-(void)deactivate;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)alertDisplayWillBecomeVisible;
-(void)setDelegate:(id)delegate;
-(void)powerDown;
-(void)cancel;
@end

