/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UIColor, UIBezierPath;

@interface SBResetProgressView : UIView {
	UIColor *_progressColor;
	UIBezierPath *_path;
	float _resetProgress;
}
+(CGSize)defaultSize;
-(void)dealloc;
-(void)setResetProgress:(float)progress;
-(id)_outlinePath;
-(id)_progressColor;
-(void)drawRect:(CGRect)rect;
@end

