/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBDismissOnlyAlertItem.h"


@interface SBReorderInfoAlert : SBDismissOnlyAlertItem {
}
-(void)didDeactivateForReason:(int)reason;
@end

