/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "APSConnectionDelegate.h"
#import <Foundation/NSObject.h>

@class NSString, NSMutableDictionary;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate> {
	NSMutableDictionary *_bundleIdentifiersToClients;
	NSMutableDictionary *_environmentsToConnections;
	unsigned _lastPlayedAlertSound;
	NSString *_lastNotificationReceivedBundleIdentifier;
}
@property(assign, getter=isSystemwideEnabled) BOOL systemwideEnabled;
@property(readonly, retain) NSString *lastNotificationReceivedBundleIdentifier;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(id)_clientsArchivePath;
-(void)saveClientState;
-(void)_purgeMissingClients;
-(void)run;
-(void)remoteNotificationAlertWasDismissedForApplication:(id)application launched:(BOOL)launched;
-(void)connection:(id)connection didReceivePublicToken:(id)token;
-(void)noteApplicationFinishedLaunching:(id)launching;
-(void)connection:(id)connection didReceiveMessageForTopic:(id)topic userInfo:(id)info;
-(id)_localizedStringFromKey:(id)key defaultValue:(id)value inBundle:(id)bundle arguments:(id)arguments;
-(void)_playAlertSound:(BOOL)sound soundName:(id)name inBundle:(id)bundle;
-(void)stopPlayingAlertSound;
-(id)allAppEnabledTypeValues;
-(id)allSettingsEnabledTypeValues;
-(void)calculateTopics;
-(void)registerApplication:(id)application forEnvironment:(id)environment withTypes:(int)types;
-(void)unregisterApplication:(id)application;
-(int)getEffectiveEnabledTypesForApplication:(id)application;
-(BOOL)hasRegisteredBundleIdentifiers;
-(void)setSettingsTypes:(int)types forBundleIdentifier:(id)bundleIdentifier;
-(id)getMessageUserInfoForBundleIdentifier:(id)bundleIdentifier;
@end

