/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"


@interface SBRestoreFailureAlertItem : SBAlertItem {
}
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(double)autoDismissInterval;
-(void)_rebootNow;
-(void)restartSystemEvent;
-(void)performUnlockAction;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)shouldShowInLockScreen;
@end

