/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class NSTimer, SBResetProgressView;

@interface SBResetView : UIView {
	SBResetProgressView *_progressView;
	NSTimer *_progressTimer;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_resetStarted:(id)started;
-(void)_resetFinished:(id)finished;
-(void)_updateProgress;
@end

