/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSString, SBApplication;

@interface SBRemoteNotificationAlert : SBAlertItem {
	SBApplication *_app;
	NSString *_body;
	NSString *_actionLabel;
	BOOL _showActionButton;
	BOOL _launched;
}
-(id)initWithApplication:(id)application body:(id)body showActionButton:(BOOL)button actionLabel:(id)label;
-(void)dealloc;
-(Class)alertSheetClass;
-(void)activateApplication;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(BOOL)willShowInAwayItems;
-(void)willDeactivateForReason:(int)reason;
@end

