/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSLock;

@interface SBResetManager : NSObject {
	BOOL _threadRunning;
	NSLock *_lock;
	int _mode;
	NSLock *_progressLock;
	float _progress;
}
@property(assign) float progress;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)setMode:(int)mode;
-(void)beginReset;
-(void)_beginReset:(id)reset;
-(void)_resetThread;
-(void)_postResetEnded;
-(void)_resetFinished;
@end

