/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSTimer, AVController;

@interface SBRingingAlertItem : SBAlertItem {
	AVController *_avController;
	NSTimer *_autoMuteTimer;
}
-(id)soundIdentifier;
-(id)_avController;
-(id)avClientName;
-(id)avAudioCategory;
-(id)avClientPriority;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)dismissOnLock;
-(float)lockLabelFontSize;
-(void)willActivate;
-(void)startRingingAndVibrating;
-(void)_stopAutoMuteTimer;
-(void)_autoMute:(id)mute;
-(void)autoMute;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)willDeactivateForReason:(int)reason;
-(void)stopRingingAndVibrating;
-(void)dealloc;
@end

