/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class UIView, UIWindow;

@interface SBScreenFlash : NSObject {
	UIWindow *_flashWindow;
	UIView *_flashView;
	BOOL _windowVisible;
}
+(id)sharedInstance;
-(void)_createUI;
-(void)_tearDown;
-(void)_orderWindowOut:(id)out;
-(void)_orderWindowFront:(id)front;
-(void)stopFlash;
-(void)flash;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void *)context;
@end

