/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "SPDaemonQueryDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UISearchBarDelegate.h"
#import "SpringBoard-Structs.h"

@class NSMutableArray, SPSearchResult, SPSearchResultDeserializer, SPDaemonQueryToken, SBSearchView, NSDate, NSTimer, NSArray, NSDateFormatter, NSString;

@interface SBSearchController : NSObject <UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, SPDaemonQueryDelegate> {
	SBSearchView *_searchView;
	NSString *_queryString;
	NSDateFormatter *_dateFormatter;
	int _domainOrdering[12];
	NSArray *_querySearchDomains;
	BOOL _querySearchDomainsIncludesApplications;
	int _sectionToGroupMap[12];
	BOOL _sectionToGroupMapIsValid;
	int _resultSectionCount;
	int _applicationsSectionIndex;
	SPSearchResult *_cursor;
	SPSearchResultDeserializer *_resultGroups[12];
	SPSearchResultDeserializer *_accumulatingResultGroups[12];
	BOOL _resultGroupsIsCurrent[12];
	SPDaemonQueryToken *_currentToken;
	NSMutableArray *_matchingLaunchingIcons;
	NSTimer *_clearSearchTimer;
	NSDate *_clearSearchDate;
	BOOL _reloadingTableContent;
}
@property(retain, nonatomic) SBSearchView *searchView;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)updateSearchOrdering;
-(void)resetClearSearchTimer;
-(void)startClearSearchTimer;
-(void)_updateClearSearchTimerFireDate;
-(void)_clearSearchTimerFired;
-(BOOL)hasQueryString;
-(BOOL)hasSearchResults;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)searchBarTextDidEndEditing:(id)searchBarText;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(BOOL)_sectionIsApp:(int *)app appOffset:(int *)offset;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)_stringFromDate:(id)date;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)_deselect;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)updateTableContents;
-(void)searchDaemonQuery:(id)query addedResults:(id)results;
-(void)searchDaemonQuery:(id)query encounteredError:(id)error;
-(void)searchDaemonQueryCompleted:(id)completed;
-(BOOL)_shouldDisplayApplicationSearchResults;
-(void)_promoteAccumulatedResults;
-(void)_releaseAccumulatingResultGroups;
-(void)_releaseResultGroups;
-(void)_updateSectionToGroupMap;
-(id)_groupForSection:(int)section;
-(int)_groupIndexForSection:(int)section;
-(int)_resultSectionCount;
-(id)_launchingURLForResult:(id)result withDisplayIdentifier:(id)displayIdentifier;
-(void)_updateApplicationSearchResults;
-(id)_imageForDomain:(int)domain andDisplayID:(id)id;
-(id)_imageForDisplayIdentifier:(id)displayIdentifier;
-(void)clearSearchResults;
@end

