/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>

@class SBProxyRemoteView, SBApplication;

@interface SBSheetView : UIView {
	SBProxyRemoteView *_remoteProxyView;
	SBApplication *_app;
}
-(id)initWithRemoteViewIdentifier:(id)remoteViewIdentifier application:(id)application;
-(id)remoteViewIdentifier;
-(id)application;
-(void)noteSheetDidEnd;
-(void)dealloc;
@end

