/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSIMToolkitTextAlertDisplay.h"


@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay {
}
+(id)createTopBarForInstance:(id)instance;
+(id)createBottomBarForInstance:(id)instance;
-(void)dismiss:(id)dismiss;
-(id)_activeCalls;
-(void)dial:(id)dial;
-(id)alertText;
@end

