/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import "SBSIMToolkitAlert.h"
#import "SBAlert.h"

@class NSTimer, AVController, AVQueue, NSString;

@interface SBSIMToolkitAlert : SBAlert {
	BOOL _needsResponse;
	NSTimer *_timeoutTimer;
	NSString *_tone;
	AVController *_avController;
	AVQueue *_avQueue;
	BOOL _interruptedAudio;
}
@property(assign) BOOL needsResponse;
+(CTServerConnectionRef)simToolkitServerConnection;
+(BOOL)wantsNextUserEvent;
+(void)userEventOccurred;
+(void)setCurrentAlert:(id)alert;
+(id)currentAlert;
+(void)dismissCurrentAlert;
+(void)test;
+(void)_idleScreenShown:(id)shown;
+(void)_stopSTKMonitor;
+(void)_startSTKMonitor;
+(void)_restartMonitor;
+(void)registerForAlerts;
-(void)sendResponse:(CFStringRef)response withString:(id)string;
-(void)sendResponse:(CFStringRef)response withBool:(BOOL)aBool;
-(void)sendResponse:(CFStringRef)response;
-(unsigned long)_soundIDForTone:(CFStringRef)tone;
-(void)_setAudioInterrupted:(BOOL)interrupted;
-(void)_playbackDidEnd:(id)_playback;
-(void)playRingtoneWithIdentifier:(id)identifier loop:(BOOL)loop;
-(void)_stopTone:(id)tone;
-(BOOL)sendResponseUponDisplay;
-(BOOL)dismissesAfterNextEvent;
-(BOOL)oneShotInputEntry;
-(void)dealloc;
-(BOOL)allowsEventOnlySuspension;
-(void)deactivate;
-(void)_playTone:(CFStringRef)tone forDuration:(float)duration;
-(CFStringRef)toolkitAlertType;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)clearTimeoutTimer;
-(BOOL)_delayEnabled;
-(void)restartTimeoutTimer:(float)timer;
-(void)startTimeoutTimerIfNecessary;
-(void)displayDidTimeout;
@end

@interface SBSIMToolkitAlert (PhoneAlert)
-(CFStringRef)callPriority;
-(CFStringRef)displayTextPriority;
-(BOOL)shouldRedial;
-(id)phoneNumber;
-(id)inCallText;
@end

