/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"


@interface SBSIMLockAlertItem : SBAlertItem {
	int _status;
}
@property(readonly, assign) int status;
+(id)alertTitleForStatus:(int)status languageCode:(id)code;
+(id)alertTitleForStatus:(int)status;
-(id)initWithStatus:(int)status;
-(void)dealloc;
-(BOOL)canUnlock;
-(id)alertTitleForLanguageCode:(id)languageCode;
-(id)alertTextForLanguageCode:(id)languageCode;
-(void)didDeactivateForReason:(int)reason;
-(void)unlock;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
@end

