/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"

@class NSString;

@interface SBSIMLockEntryAlertDisplay : SBSlidingAlertDisplay {
	NSString *_languageCode;
	NSString *_code;
}
-(id)initWithFrame:(CGRect)frame languageCode:(id)code;
-(void)dealloc;
-(id)localizedStringWithKey:(id)key;
-(id)_pinAttemptsRemainingLabel;
-(BOOL)alphanumericKeyboard;
-(void)setupUnlockAttemptState;
-(id)failureTitle;
-(id)failureLabel;
-(void)setupFailureState;
-(id)titleText;
-(id)label;
-(void)setupCurrentLockAttemptState;
-(void)alertDisplayWillBecomeVisible;
-(void)setupSuccess;
-(void)_unlock;
-(void)unlock;
-(void)phonePad:(id)pad keyUp:(BOOL)up;
-(void)passcodeFieldDidAcceptEntry:(id)passcodeField;
@end

