/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"


@interface SBSIMLockEntryAlert : SBAlert {
	int _status;
}
@property(readonly, assign) int status;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)deactivate;
@end

