/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSIMLockEntryAlertDisplay.h"
#import "SpringBoard-Structs.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertDisplay : SBSIMLockEntryAlertDisplay {
	int _state;
	NSString *_enteredPUKCode;
	NSString *_newPIN;
}
-(void)dealloc;
-(id)_pukAttemptsRemainingLabel;
-(void)setupSuccess;
-(id)titleText;
-(void)setupFailureState;
-(id)label;
-(void)_attemptPUKUnlock;
-(void)unlock;
@end

