/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"

@class SBTextDisplayView, UIScroller;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay {
	SBTextDisplayView *_contentView;
	UIScroller *_scroller;
}
+(id)createTopBarForInstance:(id)instance;
+(id)createBottomBarForInstance:(id)instance;
-(void)dealloc;
-(void)navigationBar:(id)bar buttonClicked:(int)clicked;
-(void)adjustScrollerFrame;
-(id)initWithFrame:(CGRect)frame;
-(BOOL)showsDesktopImage;
-(void)setMiddleContentAlpha:(float)alpha;
-(void)displayDidTimeout;
-(id)alertText;
-(void)alertDisplayWillBecomeVisible;
-(void)accept:(id)accept;
-(void)dismiss:(id)dismiss;
-(void)dismiss;
@end

