/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"

@class NSString, SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject {
	BOOL _isInitialUpdate;
	BOOL _isBrickedDevice;
	int _status;
	SBSIMLockAlertItem *_currentAlert;
	SBSIMLockEntryAlert *_lockEntryAlert;
	NSString *_languageCode;
}
@property(readonly, assign) int status;
@property(readonly, retain) NSString *languageCode;
+(id)sharedInstance;
-(void)dealloc;
-(BOOL)_hopelesslyPUKLocked;
-(int)_CTToSBSIMStatus:(CFStringRef)sbsimstatus;
-(int)_statusFromCT;
-(void)lockEntryAlertDismissed:(id)dismissed;
-(void)alertItemDismissed:(id)dismissed;
-(void)repopAlert;
-(void)attemptUnlock;
-(void)_updateToStatus:(int)status;
-(void)_tryToUpdateStatus;
-(void)_tearDownAlertAndUpdateStatus;
-(void)_updateSIMStatus:(CFStringRef)status withOptions:(CFDictionaryRef)options;
-(int)pinLockAttemptsRemaining;
-(int)pukLockAttemptsRemaining;
-(void)_initialUpdate;
-(void)_lockdownChanged;
-(void)registerForAlerts;
@end

