/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSIMToolkitGetInputDisplay.h"
#import "SpringBoard-Structs.h"


@interface SBSIMToolkitOneShotGetInputDisplay : SBSIMToolkitGetInputDisplay {
}
+(id)createBottomBarForInstance:(id)instance;
-(BOOL)textField:(id)field shouldInsertText:(id)text replacingRange:(NSRange)range;
@end

