/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertInputView.h"


@interface SBSIMToolkitGetInputDisplay : SBAlertInputView {
}
-(void)navigationBar:(id)bar buttonClicked:(int)clicked;
-(void)alertDisplayWillBecomeVisible;
-(void)displayDidTimeout;
-(void)sbAlertInputViewSendClicked:(id)clicked;
-(void)sbAlertInputViewCancelClicked:(id)clicked;
@end

