/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBUSSDAlert.h"


@interface SBSMSClass0Alert : SBUSSDAlert {
}
+(void)registerForAlerts;
-(void)_unregisterForNotifications;
-(void)_registerForNotifications;
-(id)initWithString:(id)string;
@end

