/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class UIImage, UIImageView;

@interface SBStatusBarBluetoothView : SBStatusBarContentView {
	UIImage *_icon;
	BOOL _animating;
	UIImageView *_activeView;
	UIImageView *_baseLayer;
	BOOL _isStarted;
	BOOL _showBluetoothView;
}
@property(assign, getter=isVisible) BOOL visible;
@property(readonly, retain) UIImage *icon;
+(void)initialize;
-(id)init;
-(int)_effectiveMode;
-(void)_setupActiveView;
-(int)btStatus;
-(void)_btStatusChanged:(id)changed;
-(void)_btDeviceConnected;
-(void)_btConnectionStatusChanged:(id)changed;
-(void)_btDeviceDisconnected:(id)disconnected;
-(void)animationDidStop:(id)animation;
-(void)_start;
-(void)_btPowerPrefChanged:(id)changed;
-(void)start;
-(void)stop;
-(int)priority;
-(void)dealloc;
-(float)padding;
@end

