/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray, SBStatusBar, SBStatusBarContentsView, UIColor, UIWindow;

@interface SBStatusBarController : NSObject {
	UIWindow *_slidingStatusBarWindow;
	int _slidingStatusBarAnimation;
	UIWindow *_animatingCallStatusBarWindow;
	UIWindow *_leftBottomCorner;
	UIWindow *_rightBottomCorner;
	SBStatusBar *_statusBarView;
	SBStatusBarContentsView *_statusBarContentsView;
	SBStatusBar *_transitioningStatusBarView;
	SBStatusBar *_animatingCallStatusBar;
	SBStatusBar *_animatingCallStatusBarToFixUp;
	SBStatusBarContentsView *_transitioningStatusBarContentsView;
	unsigned _isLockVisible : 1;
	unsigned _isTimeVisible : 1;
	unsigned _lockOrTimeVisibleChanging : 1;
	unsigned _dimmed : 1;
	unsigned _showDimmerOverlay : 1;
	unsigned _animating : 1;
	unsigned _airplaneMode : 1;
	unsigned _showsProgress : 1;
	unsigned _showsProgressOnHomeScreen : 1;
	unsigned _cloakStatusBar : 1;
	unsigned _showAirport : 1;
	unsigned _telephonyControllerCheckedIn : 1;
	unsigned _bluetoothControllerCheckedIn : 1;
	unsigned _enteringAirplaneMode : 1;
	unsigned _doubleHeightStatusBarHeightDirty : 1;
	unsigned _doubleHeightStatusBarContentDirty : 1;
	unsigned _animatingStatusBarRotation : 1;
	NSMutableArray *_statusBarIndicatorNames;
	int _mode;
	int _orientation;
	int _animatingCallStatusBarOrientation;
	NSString *_customText;
	UIColor *_dimmerOverlayColor;
	int _airPortSignalStrength;
	NSMutableArray *_doubleHeightInfos;
}
@property(assign) BOOL dimmed;
@property(assign) BOOL showDimmerOverlay;
@property(retain) UIColor *dimmerOverlayColor;
@property(assign) BOOL isInCall;
@property(assign) BOOL airplaneModeIsEnabled;
@property(retain) NSString *customText;
@property(assign) int airPortStrength;
@property(assign) BOOL showsAirPort;
@property(assign) BOOL cloakStatusBar;
@property(readonly, retain) SBStatusBar *statusBarView;
@property(readonly, retain) SBStatusBar *transitioningStatusBarView;
@property(readonly, retain) NSMutableArray *statusBarIndicatorNames;
+(id)sharedStatusBarController;
+(BOOL)isLikeAFullScreenStatusBar:(int)bar;
+(id)statusBarImageNamed:(id)named forMode:(int)mode;
-(id)init;
-(BOOL)_enteringAirplaneMode;
-(void)dealloc;
-(void)preheatStatusBarForMode:(int)mode orientation:(int)orientation;
-(id)statusBarWindow;
-(void)addStatusBarItem:(id)item;
-(void)setIsLockVisible:(BOOL)visible isTimeVisible:(BOOL)visible2;
-(BOOL)isLockVisible;
-(BOOL)isTimeVisible;
-(BOOL)isLockOrTimeVisibleChanging;
-(void)tearDownWindowForSlidingStatusBar:(id)slidingStatusBar overStatusBar:(id)bar;
-(void)setupWindowForSlidingStatusBar:(id)slidingStatusBar overStatusBar:(id)bar;
-(void)endDoubleHeightStatusBarAnimationFinished;
-(void)resizeStatusBar:(float)bar grow:(BOOL)grow fenceID:(int)id;
-(BOOL)useDoubleHeightSizeForMode:(int)mode orientation:(int)orientation;
-(BOOL)useDoubleHeightStyle;
-(BOOL)useDoubleHeightSize;
-(void)updateDoubleHeightStatusBarState;
-(id)doubleHeightInfoForBundleID:(id)bundleID createIfNeeded:(BOOL)needed;
-(void)setDoubleHeightMode:(int)mode glowAnimationEnabled:(BOOL)enabled bundleID:(id)id;
-(void)setDoubleHeightMode:(int)mode glowAnimationEnabled:(BOOL)enabled bundleID:(id)id priority:(int)priority;
-(void)clearDoubleHeightStatusBarForBundleID:(id)bundleID;
-(int)doubleHeightMode;
-(void)setDoubleHeightPrefixText:(id)text bundleID:(id)id;
-(id)doubleHeightPrefixText;
-(void)setDoubleHeightStatusText:(id)text bundleID:(id)id;
-(id)doubleHeightStatusText;
-(BOOL)_isServiceAvailable;
-(id)_SIMStatus;
-(void)_SIMOrServiceStatusChanged;
-(void)_SIMStatusChanged:(id)changed;
-(void)_serviceStatusChanged:(id)changed;
-(void)removeStatusBarItem:(id)item;
-(void)dataConnectionTypeChanged;
-(void)updateProgressVisibility;
-(BOOL)showsProgress;
-(void)setShowsProgressOnHomeScreen:(BOOL)screen;
-(void)setStatusBarMode:(int)mode orientation:(int)orientation duration:(double)duration animation:(int)animation;
-(void)setStatusBarMode:(int)mode orientation:(int)orientation duration:(double)duration fenceID:(int)id animation:(int)animation startTime:(double)time;
-(void)_setTransitionalStatusBarSize:(BOOL)size;
-(void)statusBarRotateContentAnimationDidStop:(id)statusBarRotateContentAnimation finished:(id)finished context:(id)context;
-(void)finishSwitching;
-(void)switchBackstopFrom:(int)from to:(int)to fromOrientation:(int)orientation toOrientation:(int)orientation4 duration:(double)duration fenceID:(int)id animation:(int)animation startTime:(double)time;
-(void)orderStatusBarFront;
-(void)_finishStatusBarAnimation;
-(void)lockCurrentStatusBarForAnimation;
-(void)releaseLockedStatusBarForAnimationForDisplay:(id)display;
-(int)statusBarMode;
-(int)statusBarOrientation;
-(void)significantTimeChange;
-(void)updateClockFormat;
-(void)signalFormatChanged;
-(void)showBatteryPercentageChanged;
-(void)checkInController:(int)controller;
-(BOOL)telephonyControllerCheckedIn;
-(BOOL)bluetoothControllerCheckedIn;
-(void)loopCarrierNameIfNecessary;
@end

