/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class NSString;

@interface SBStatusBarNoServiceView : SBStatusBarContentView {
	NSString *_errorString;
	BOOL _showNoServiceView;
}
@property(assign, getter=isVisible) BOOL visible;
@property(readonly, retain) NSString *errorString;
+(id)displayStringForSIMStatus:(id)simstatus;
+(id)displayStringForRegistrationStatus:(int)registrationStatus;
-(id)initWithErrorString:(id)errorString;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(id)textFont;
-(int)priority;
-(float)padding;
@end

