/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class UIView;

@interface SBStatusWindow : UIWindow {
	UIView *_holderView;
}
@property(readonly, retain) UIView *holderView;
+(CGRect)constrainFrameToScreen:(CGRect)screen;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

