/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarDoubleHeightView.h"
#import "SpringBoard-Structs.h"

@class NSTimer;

@interface SBStatusBarInCallView : SBStatusBarDoubleHeightView {
	double _inCallDuration;
	NSTimer *_durationTimer;
}
-(void)dealloc;
-(void)start;
-(void)stop;
-(void)drawRect:(CGRect)rect;
@end

