/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class NSString, UIFont;

@interface SBStatusBarDoubleHeightView : SBStatusBarContentView {
	NSString *_durationPreamble;
	CGSize _durationPreambleSize;
	UIFont *_font;
}
-(id)init;
-(void)dealloc;
@end

