/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class NSString, NSTimer;

@interface SBStatusBarTimeView : SBStatusBarContentView {
	NSTimer *_dateTimer;
	NSString *_time;
	CGRect _textRect;
}
@property(readonly, assign) CGRect textRect;
-(id)init;
-(void)updateClockFormat;
-(void)dealloc;
-(void)start;
-(void)stop;
-(int)priority;
-(void)drawRect:(CGRect)rect;
-(void)tile;
-(float)timeViewWidth;
@end

