/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/Foundation.h>

@class SBStatusWindow, SBStatusBarDoubleHeightView, SBStatusBarContentsView, UIView;

@interface SBStatusBar : UIControl {
	int _mode;
	int _orientation;
	SBStatusBarContentsView *_contentsView;
	SBStatusBarDoubleHeightView *_doubleHeightView;
	SBStatusWindow *_statusWindow;
	UIView *_airplaneView;
	UIView *_baseDoubleHeightColorView;
	UIView *_glowDoubleheightColorView;
	UIView *_dimmerView;
	int _doubleHeightMode;
	unsigned _animating : 1;
	unsigned _glowAnimationEnabled : 1;
	unsigned _isPressed : 1;
	unsigned _airplaneMode : 1;
}
@property(assign, nonatomic, getter=isGlowAnimationEnabled) BOOL glowAnimationEnabled;
@property(retain) SBStatusWindow *statusWindow;
@property(readonly, assign) int mode;
@property(readonly, assign) int orientation;
@property(readonly, retain) SBStatusBarContentsView *contentsView;
@property(readonly, retain) UIView *airplaneView;
-(id)initWithMode:(int)mode orientation:(int)orientation;
-(id)description;
-(void)_setGlowImage:(id)image;
-(void)_setBaseImage:(id)image;
-(void)updateDoubleHeightView;
-(void)dealloc;
-(CGAffineTransform)distantStatusWindowTransform;
-(void)drawRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(void)start;
-(void)stop;
-(void)showDimmerOverlay:(BOOL)overlay;
-(void)setDimmerOverlayColor:(id)color;
-(void)startGlowAnimation;
-(void)stopGlowAnimation;
-(void)setAirplaneModeIsEnabled:(BOOL)enabled animate:(BOOL)animate ignoreAirPortPower:(BOOL)power;
-(void)setAirplaneModeIsEnabled:(BOOL)enabled animate:(BOOL)animate;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)beginTrackingAt:(CGPoint)at withEvent:(GSEventRef)event;
-(BOOL)isDimmed;
-(void)statusBarClicked;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

