/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"

@class SBStatusBarContentsView;

@interface SBStatusBarContentView : UIView {
	SBStatusBarContentsView *_contentsView;
	int _mode;
}
@property(assign, getter=isVisible) BOOL visible;
@property(assign) BOOL showOnLeft;
@property(assign) float overlap;
-(id)initWithContentsView:(id)contentsView;
-(id)initWithFrame:(CGRect)frame;
-(void)setMode:(int)mode;
-(int)effectiveModeForImages;
-(void)start;
-(void)stop;
-(id)textFont;
-(void)drawText:(id)text atPoint:(CGPoint)point forWidth:(float)width lineBreakMode:(int)mode;
-(void)enableShadow;
-(int)priority;
-(int)compare:(id)compare;
-(float)padding;
@end

