/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"


@interface SBStatusBarBluetoothBatteryView : SBStatusBarContentView {
	BOOL _showBluetoothBatteryView;
}
@property(assign, getter=isVisible) BOOL visible;
-(id)init;
-(void)start;
-(void)stop;
-(void)batteryLevelChanged;
-(void)drawRect:(CGRect)rect;
-(int)priority;
-(float)padding;
@end

