/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"


@interface SBStatusBarBatteryPercentageView : SBStatusBarContentView {
	int _displayedCapacity;
	BOOL _isOnAC;
	BOOL _showBatteryPercentageView;
}
@property(assign, getter=isVisible) BOOL visible;
-(id)init;
-(void)updateBattery;
-(void)_batteryStatusChanged:(id)changed;
-(void)dealloc;
-(void)start;
-(void)stop;
-(int)priority;
-(void)drawRect:(CGRect)rect;
-(float)padding;
@end

