/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class NSString, UIImage, SBStatusBarOperatorNameView;

@interface SBStatusBarCarrierView : SBStatusBarContentView {
	UIImage *_operatorIcon;
	SBStatusBarOperatorNameView *_operatorNameView;
	NSString *_operatorName;
	BOOL _operatorNameIsLooping;
	BOOL _showCarrierView;
}
@property(assign, getter=isVisible) BOOL visible;
-(id)init;
-(void)dealloc;
-(void)start;
-(void)stop;
-(int)priority;
-(void)clearLastOperatorNameLooped;
-(void)loopOperatorNameToBeginning:(id)beginning didFinish:(id)finish;
-(void)loopOperatorNameToEnd;
-(void)finishedLoopingOperatorName:(id)name didFinish:(id)finish;
-(void)startOperatorNameLooping:(id)looping;
-(void)loopIfNecessary;
-(void)_setOperatorName:(id)name;
-(void)setOperatorName:(id)name;
-(id)_imageForOperatorName:(id)operatorName statusBarIsFullScreenOpaque:(BOOL)opaque;
-(id)operatorIconForName:(id)name;
-(CGSize)defaultSize;
-(void)operatorNameChanged;
-(void)operatorBundleChanged;
-(float)padding;
@end

