/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBStatusBarContentView.h"
#import "SpringBoard-Structs.h"

@class UIProgressIndicator;

@interface SBStatusBarProgressView : SBStatusBarContentView {
	UIProgressIndicator *_progressIndicator;
	BOOL _wasLastUsingASlowConnection;
	BOOL _showProgressView;
	BOOL _showOnLeft;
}
@property(assign, getter=isVisible) BOOL visible;
@property(assign) BOOL showOnLeft;
-(id)init;
-(void)dealloc;
-(void)dataConnectionTypeChanged;
-(void)start;
-(void)stop;
-(void)progressChanged;
-(int)priority;
-(float)padding;
@end

