/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"


@interface SBSyncController : NSObject {
	int _syncState;
	int _restoreState;
	int _resetState;
	int _sofwareUpdateState;
	CFMachPortRef _backupAgentCFPort;
	BOOL _showingResetUI;
}
@property(readonly, assign) int syncState;
@property(readonly, assign) int restoreState;
@property(readonly, assign) int resetState;
+(id)sharedInstance;
-(void)dealloc;
-(void)startObserving;
-(void)stopObserving;
-(BOOL)isSyncing;
-(void)didEndSyncing;
-(void)suspendSyncing;
-(void)resumeSyncing;
-(void)cancelSyncing;
-(void)_notifyAppsSyncWillBegin;
-(void)didShowSyncPanel;
-(void)frontLockedWhenPossible;
-(void)beginSyncing;
-(void)iTunesSyncRequestedStart;
-(void)iTunesSyncPhaseDidFinish:(int)iTunesSyncPhase reason:(int)reason;
-(BOOL)isRestoring;
-(void)_notifyRestoreCanProceed;
-(void)_killApplications;
-(void)beginRestoring;
-(void)finishedTerminatingApplications;
-(void)cancelRestoring;
-(void)_rebootNow;
-(void)finishEndRestoring;
-(void)didEndRestoring:(int)restoring;
-(BOOL)isResetting;
-(void)_delayedQuitApplications;
-(void)_delayedBeginReset;
-(void)beginResetting:(BOOL)resetting;
-(void)didEndResetting;
-(void)_resetStarted:(id)started;
-(void)_resetEnded:(id)ended;
-(void)_invalidateBackupAgentCFPort;
-(void)_didEndRestoringWithRestoreFailed;
-(BOOL)_setupBackupAgentPort;
-(void)setSoftwareUpdateState:(int)state;
-(void)showPreSoftwareUpdateScreen;
-(BOOL)isSoftwareUpdating;
-(BOOL)isInUse;
@end

