/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface SBTelephonyManager : NSObject {
	void *_suspendDormancyAssertion;
	NSString *_operatorName;
	unsigned _suspendDormancyEnabled;
	unsigned _usingWifi : 1;
	unsigned _usingVPN : 1;
	unsigned _iTunesNeedsToRecheckActivation : 1;
	unsigned _pretendingToSearch : 1;
	unsigned _callForwardingIndicator : 2;
	unsigned _usingWirelessModem : 1;
}
@property(assign) int callForwardingIndicator;
@property(assign, getter=isNetworkRegistrationEnabled) BOOL networkRegistrationEnabled;
@property(assign) BOOL isUsingWiFiConnection;
@property(assign) BOOL isUsingVPNConnection;
@property(retain) NSString *operatorName;
@property(assign) BOOL isUsingWirelessModem;
+(id)sharedTelephonyManager;
-(id)init;
-(CTServerConnectionRef)_serverConnection;
-(void)_serverConnectionDidError:(XXStruct_K5nmsA)_serverConnection;
-(void)SBTelephonyDaemonRestartHandler;
-(void)updatePhoneNumberPrefs;
-(void)updateTTYIndicator;
-(double)inCallDuration;
-(void)updateCallForwardingIndicator;
-(void)updateSpringBoard;
-(void)setLimitTransmitPowerPerBandEnabled:(BOOL)enabled;
-(void)setFastDormancySuspended:(BOOL)suspended;
-(void)updateAirplaneMode;
-(void)updateCalls;
-(void)_updateState;
-(BOOL)updateLocale;
-(BOOL)updateNetworkLocale;
-(void)handleSIMReady;
-(id)urlWithScheme:(id)scheme fromDialingNumber:(id)dialingNumber abUID:(int)uid urlPathAddition:(id)addition;
-(id)displayForOutgoingCallURL:(id)outgoingCallURL;
-(void)_delayedAudioResume;
-(long long)getRowIDOfLastCallInsert;
-(id)allMissedCallsAfterRowID:(long long)id;
-(int)callCount;
-(BOOL)activeCallExists;
-(BOOL)heldCallExists;
-(BOOL)incomingCallExists;
-(BOOL)outgoingCallExists;
-(BOOL)inCallUsingReceiver;
-(BOOL)callWouldUseReceiver:(BOOL)receiver;
-(BOOL)shouldHangUpOnLock;
-(BOOL)inCall;
-(void)disconnectIncomingCall;
-(void)answerIncomingCall;
-(void)answerIncomingCallEndingOthers;
-(void)swapCalls;
-(void)disconnectAllCalls;
-(void)disconnectCall;
-(void)disconnectCallAndActivateHeld;
-(void)unmute;
-(void)dumpBasebandState:(id)state;
-(BOOL)MALoggingEnabled;
-(void)powerOffRadio;
-(int)dataConnectionType;
-(BOOL)EDGEIsOn;
-(BOOL)isUsingDataConnection;
-(void)copyICCID:(id *)iccid IMEI:(id *)imei;
-(void)configureForTTY:(BOOL)tty;
-(BOOL)shouldPromptForTTY;
-(id)ttyTitle;
-(void)_resetCTMMode;
-(void)_headphoneChanged:(id)changed;
-(void)_proximityChanged:(id)changed;
-(void)_setRegistrationStatus:(int)status;
-(void)_updateRegistrationNow;
-(void)_cancelFakeService;
-(void)_startFakeServiceIfNecessary;
-(void)_stopFakeService;
-(BOOL)_pretendingToSearch;
-(id)_fetchOperatorName;
-(void)_reallySetOperatorName:(id)name;
-(void)operatorBundleChanged;
-(int)registrationStatus;
-(void)checkForRegistrationSoon;
-(id)SIMStatus;
-(int)registrationCauseCode;
-(void)noteSIMUnlockAttempt;
-(void)noteWirelessModemChanged;
@end

