/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@interface SBTetherController : NSObject {
	int _tetherState;
	unsigned _demoCardConnection;
}
+(id)sharedInstance;
-(unsigned)_demoCardConnection;
-(BOOL)isTethered;
-(void)noteInterfaceOrientationChanged;
-(void)setDitheringEnabled:(int)enabled;
-(void)updatePreferencesIfNeeded;
@end

