/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay {
}
+(id)createTopBarForInstance:(id)instance;
+(id)createBottomBarForInstance:(id)instance;
-(id)initWithSize:(CGSize)size;
-(void)_makeCall;
-(void)_chooseVoiceMode:(id)mode;
-(void)_chooseTTYMode:(id)mode;
-(void)_ignore:(id)ignore;
@end

