/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBTVOutController.h"
#import <Foundation/NSObject.h>


@interface SBTVOutController : NSObject {
	int _tvOutMode;
}
@property(assign, nonatomic) int tvOutMode;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)setIntialTVModeIfNeeded;
-(void)updateLayerKitSettings;
-(void)updateSettings;
@end

@interface SBTVOutController (private)
-(void)_handleIapServerConnectionDied;
-(void)startListeningForSettingsChanges;
-(void)stopListeningForSettingsChanges;
@end

