/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@interface SBUserNotificationCenter : NSObject {
}
+(void)startUserNotificationCenter;
+(void)_userNotificationDone:(id)done;
@end

