/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UITextFieldDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class UITextField, TPBottomButtonBar, UITransitionView, UIScroller, SBTextDisplayView, UIProgressIndicator;

@interface SBUSSDAlertDisplay : SBAlertDisplay <UITextFieldDelegate> {
	TPBottomButtonBar *_responseBar;
	UIView *_notifyView;
	UIView *_replyView;
	UITransitionView *_transitionView;
	UIScroller *_scroller;
	SBTextDisplayView *_contentView;
	SBTextDisplayView *_charsRemainingView;
	UIProgressIndicator *_progressIndicator;
	UITextField *_responseField;
	BOOL _allowsResponse;
}
@property(assign) BOOL allowsResponse;
-(id)initWithFrame:(CGRect)frame;
-(id)_notifyView;
-(id)_replyView;
-(void)dealloc;
-(void)displayString:(id)string centerVertically:(BOOL)vertically;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
-(void)_setupResponseBar;
-(void)alertStringAvailable:(id)available;
-(BOOL)textField:(id)field shouldInsertText:(id)text replacingRange:(NSRange)range;
-(void)_updateCharsRemaining;
-(void)_textChanged:(id)changed;
-(void)_replyClicked;
-(void)_okayClicked;
-(void)_cancelClicked;
-(void)navigationBar:(id)bar buttonClicked:(int)clicked;
@end

