/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"


@interface SBVoiceControlAlert : SBAlert {
}
+(void)registerForAlerts;
+(BOOL)shouldEnterVoiceControl;
+(BOOL)resetVoiceControlIfNecessary:(BOOL)necessary;
+(void)setNextRecognitionAudioInputPaths:(id)paths;
-(void)_setRoutingAttributesForWiredHeadset;
-(id)init;
-(id)initFromWiredHeadsetButton;
-(BOOL)allowsEventOnlySuspension;
-(void)deactivate;
-(void)deactivateAfterLocking;
-(id)initFromMenuButton;
-(void)dealloc;
-(void)_proximityChanged:(id)changed;
-(void)handleHeadsetButtonUpFromActivation:(BOOL)activation;
-(void)handleMenuButtonTap;
-(double)autoDimTime;
-(id)alertDisplayViewWithSize:(CGSize)size;
@end

