/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"
#import "UIModalViewDelegate.h"

@class SBVODAlarm;

@interface SBVODAlertItem : SBAlertItem <UIModalViewDelegate> {
	SBVODAlarm *_alarm;
}
+(id)activeAlertForAlarm:(id)alarm;
-(void)dealloc;
-(void)setAlarm:(id)alarm;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)unlocksScreen;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)screenWillUndim;
-(void)willActivate;
-(void)willDeactivateForReason:(int)reason;
-(void)_updateText;
@end

