/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSDictionary;

@interface SBVODAlarm : NSObject {
	NSString *_title;
	NSString *_path;
	NSDictionary *_rentalInfo;
	unsigned _loadingRentalInfo : 1;
	unsigned _sanityCheckingExpiration : 1;
	unsigned _watched : 1;
}
@property(readonly, retain) NSString *title;
@property(readonly, retain) NSString *path;
+(void)cancelPendingLoads;
+(void)_rentalInfoThread;
-(id)initWithDictionary:(id)dictionary;
-(void)dealloc;
-(int)compare:(id)compare;
-(id)expirationDate;
-(BOOL)hasLoaded;
-(BOOL)isExpired;
-(BOOL)rentalHasBeenWatched;
-(BOOL)hasFireDateSinceDate:(id)date;
-(id)nextFireDate;
-(void)sanityCheckExpiration;
-(id)_dateWithStartDate:(id)startDate duration:(id)duration;
-(id)_rentalInfo;
-(void)_setRentalInfo:(id)info;
@end

