/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>

@class NSTimer, NSMutableDictionary;

@interface SBWiFiManager : NSObject {
	WiFiManagerClientRef _manager;
	WiFiDeviceClientRef _device;
	WiFiNetworkRef _currentNetwork;
	BOOL _currentNetworkHasBeenSet;
	BOOL _powered;
	BOOL _poweredHasBeenSet;
	int _rssiThreshold;
	BOOL _joining;
	int _signalStrengthBars;
	BOOL _signalStrengthHasBeenSet;
	NSTimer *_signalStrengthTimer;
	int _shouldPollSignalStrength;
	BOOL _canPollSignalStrength;
	NSMutableDictionary *_securityDict;
	id _delegate;
	unsigned _notificationID;
	double _lastSignalStrengthUpdateTime;
}
@property(assign) BOOL wiFiEnabled;
@property(readonly, assign) BOOL powered;
@property(readonly, assign) BOOL joining;
@property(readonly, assign) int signalStrengthBars;
+(id)sharedInstance;
+(BOOL)hasWiFi;
-(void)dealloc;
-(WiFiManagerClientRef)_manager;
-(id)init;
-(void)setDelegate:(id)delegate;
-(void)scan;
-(void)dismissAlerts;
-(void)_powerStateDidChange;
-(void)_linkDidChange;
-(void)_updateCurrentNetwork;
-(BOOL)isAssociated;
-(BOOL)_cachedIsAssociated;
-(id)currentNetworkName;
-(void)updateSignalStrength;
-(void)_updateSignalStrengthTimer;
-(void)beginPollingForSignalStrength;
-(void)endPollingForSignalStrength;
-(void)cancelTrust:(BOOL)trust;
-(void)acceptTrust:(id)trust;
-(void)cancelPicker:(BOOL)picker;
-(void)userChoseNetwork:(id)network;
-(id)knownNetworks;
-(BOOL)networkRequiresPassword:(id)password;
-(void)resetSettings;
-(void)_scanComplete:(CFArrayRef)complete;
-(void)_joinComplete:(int)complete network:(WiFiNetworkRef)network;
-(void)joinNetwork:(id)network password:(id)password;
-(void)_askToJoinWithID:(unsigned)id;
-(void)_trustCallbackWithID:(unsigned)id type:(int)type network:(WiFiNetworkRef)network data:(id)data;
@end

