/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>
#import "SpringBoard-Structs.h"


@interface SBWiFiCell : UIAlertSheetTableCell {
	id _userInfo;
}
@property(retain) id userInfo;
-(id)initWithFrame:(CGRect)frame networkDictionary:(id)dictionary;
-(void)layoutSubviews;
-(void)updateHighlightColors;
@end

