/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBWiFiErrorAlertItem : SBAlertItem {
	id _delegate;
	NSString *_name;
	int _error;
}
-(id)initWithNetworkName:(id)networkName error:(int)error;
-(void)dealloc;
-(void)setDelegate:(id)delegate;
-(void)dismiss;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

