/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/Foundation.h>


@interface SMSAlertSheet : UIModalView {
	BOOL _showingTagline;
	BOOL _showingImage;
}
@property(readonly, assign) BOOL showingImage;
-(void)layout;
-(void)setImageData:(id)data;
-(void)updateTagline;
-(void)layoutAnimated:(BOOL)animated;
@end

