/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */



@protocol SPDaemonQueryDelegate
-(void)searchDaemonQuery:(id)query addedResults:(id)results;
-(void)searchDaemonQuery:(id)query encounteredError:(id)error;
-(void)searchDaemonQueryCompleted:(id)completed;
@end

