/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

typedef struct __GSEvent *GSEventRef;

typedef struct __CTCall *CTCallRef;

typedef struct SBApplicationTimes {
	double _field1;
	double _field2;
	double _field3;
	double _field4;
	double _field5;
	double _field6;
	double _field7;
} SBApplicationTimes;

typedef struct _MISProfile *MISProfileRef;

typedef struct {
	int _field1;
	int _field2;
} XXStruct_K5nmsA;

typedef struct __CTServerConnection *CTServerConnectionRef;

typedef struct __GSFont *GSFontRef;

typedef struct __WiFiManagerClient *WiFiManagerClientRef;

typedef struct __WiFiDeviceClient *WiFiDeviceClientRef;

typedef struct __WiFiNetwork *WiFiNetworkRef;

typedef struct {
	unsigned char voicemailAvailable;
	int voicemailCount;
	long long voicemailID;
} XXStruct_EX3dgA;

typedef struct CGContext *CGContextRef;

typedef struct {
	int _field1;
	BOOL _field2;
	BOOL _field3;
	BOOL _field4;
	BOOL _field5;
	double _field6;
} XXStruct_fhKmAA;

typedef struct CalEventExpirationMonitor *CalEventExpirationMonitorRef;

typedef struct CalAlarmEngine *CalAlarmEngineRef;

typedef struct CalDatabase *CalDatabaseRef;

typedef struct {
	unsigned _field1[8];
} XXStruct_kUSYWB;

